
version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - captin
    ports:
      - "3100:4000"
  captin:
    build: .
    image: captin:dev
    environment: 
      - CAPTIN_PORT=3000
      - CAPTIN_REDIS_HOST=redis
    expose: 
      - 3000
    depends_on: 
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
